### PR TITLE
Port to ROS 2 Dashing

### PR DESCRIPTION
**Pull request by clalancette**
This pull request does a port of imu_vn_100 to ROS 2.  A couple of notes about this port:

1.  This PR is currently targeted at master, but that's only because I don't have anything else to target it at.  I'd suggest making a new branch called `dashing`, and I can retarget the PR at that.
1.  I've removed the diagnostics code in this port.  This is because ROS 2 doesn't currently have diagnostics; we can add this back later on.
1.  I've also removed the launch file, since ROS 2 launch is pretty different.  I could do a port of the launch file to the python-based launch in ROS 2 if you prefer.

I've tested this code with a VN-100T Rugged, and things seem to be working well.  Any comments or questions about this port are welcome!

### CODE REVIEW

**Comment by versatran01** [comment]
I created a new branch as suggested.

**Comment by clalancette** [comment]
> I created a new branch as suggested.

Thanks!  I've retargetted the PR.

**Comment by clalancette** [comment]
Fantastic, thanks for merging!

**Comment by versatran01** [comment]
np, thanks for the work.

**Pull request merged**
